<?php
namespace App\Services;
use App\Models\{GoodsReceipt,Product,PurchaseOrder,PurchaseRequisition,StockHistory};
use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class PurchaseManagementService {
 public function createRequisition(array $data,int $userId):PurchaseRequisition{return DB::transaction(function()use($data,$userId){$r=PurchaseRequisition::create(['requisition_number'=>$data['requisition_number'],'department'=>$data['department']??null,'required_date'=>$data['required_date']??null,'status'=>'submitted','reason'=>$data['reason']??null,'requested_by'=>$userId]); foreach($data['items'] as $x)$r->items()->create($x); return $r->load('items.product','requester');});}
 public function approveRequisition(PurchaseRequisition $r,int $userId):PurchaseRequisition{$r->update(['status'=>'approved','approved_by'=>$userId,'approved_at'=>now()]);return $r->refresh();}
 public function createOrder(array $data,int $userId):PurchaseOrder{return DB::transaction(function()use($data,$userId){$subtotal=0;$items=[];foreach($data['items'] as $x){$line=round((int)$x['ordered_quantity']*(float)$x['unit_price'],2);$subtotal+=$line;$items[]=['product_id'=>$x['product_id'],'ordered_quantity'=>$x['ordered_quantity'],'received_quantity'=>0,'unit_price'=>$x['unit_price'],'subtotal'=>$line];}$discount=max(0,(float)($data['discount']??0));$tax=max(0,(float)($data['tax']??0));$shipping=max(0,(float)($data['shipping']??0));$po=PurchaseOrder::create(['po_number'=>$data['po_number'],'supplier_id'=>$data['supplier_id'],'purchase_requisition_id'=>$data['purchase_requisition_id']??null,'warehouse_id'=>$data['warehouse_id']??null,'order_date'=>$data['order_date'],'expected_date'=>$data['expected_date']??null,'status'=>'draft','subtotal'=>$subtotal,'discount'=>$discount,'tax'=>$tax,'shipping'=>$shipping,'total'=>round($subtotal-$discount+$tax+$shipping,2),'terms'=>$data['terms']??null,'note'=>$data['note']??null,'created_by'=>$userId]);$po->items()->createMany($items);return $po->load('items.product','supplier','warehouse');});}
 public function approveOrder(PurchaseOrder $po,int $userId):PurchaseOrder{$po->update(['status'=>'approved','approved_by'=>$userId,'approved_at'=>now()]);return $po->refresh();}
 public function receive(PurchaseOrder $po,array $data,int $userId):GoodsReceipt{return DB::transaction(function()use($po,$data,$userId){$po=PurchaseOrder::query()->lockForUpdate()->with('items')->findOrFail($po->id);if(!in_array($po->status,['approved','partially_received']))throw ValidationException::withMessages(['purchase_order'=>'Only approved purchase orders can be received.']);$grn=GoodsReceipt::create(['grn_number'=>$data['grn_number'],'purchase_order_id'=>$po->id,'warehouse_id'=>$data['warehouse_id']??$po->warehouse_id,'received_date'=>$data['received_date'],'supplier_invoice_number'=>$data['supplier_invoice_number']??null,'supplier_invoice_date'=>$data['supplier_invoice_date']??null,'due_date'=>$data['due_date']??null,'status'=>'received','note'=>$data['note']??null,'received_by'=>$userId]);foreach($data['items'] as $row){$qty=(int)($row['quantity']??0);if($qty<=0)continue;$item=$po->items->firstWhere('id',(int)$row['purchase_order_item_id']);if(!$item||$qty>$item->remaining_quantity)throw ValidationException::withMessages(['items'=>'Receive quantity exceeds remaining quantity.']);$grn->items()->create(['purchase_order_item_id'=>$item->id,'product_id'=>$item->product_id,'quantity'=>$qty,'unit_price'=>$item->unit_price,'subtotal'=>round($qty*(float)$item->unit_price,2)]);$item->increment('received_quantity',$qty);$product=Product::query()->lockForUpdate()->findOrFail($item->product_id);$before=(int)$product->stock_quantity;$after=$before+$qty;$product->update(['stock_quantity'=>$after]);StockHistory::create(['product_id'=>$product->id,'user_id'=>$userId,'type'=>'IN','quantity'=>$qty,'stock_before'=>$before,'stock_after'=>$after,'reference'=>$grn->grn_number,'note'=>'Goods received against '.$po->po_number]);}$po->refresh()->load('items');$all=$po->items->every(fn($i)=>(int)$i->received_quantity>=(int)$i->ordered_quantity);$any=$po->items->sum('received_quantity')>0;$po->update(['status'=>$all?'received':($any?'partially_received':'approved')]);return $grn->load('items.product','purchaseOrder.supplier','receiver');});}
}
