import { Head, Link, router } from "@inertiajs/react";
import { useEffect, useState } from "react";
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout";
import Pagination from "@/Components/Pagination";

export default function Index({ groups, filters = {} }) {
    const [search, setSearch] = useState(filters.search || "");
    const [status, setStatus] = useState(filters.status ?? "");
    useEffect(() => { const timeout = setTimeout(() => router.get(route("admin.customer-groups.index"), { search, status }, { preserveState: true, replace: true }), 350); return () => clearTimeout(timeout); }, [search, status]);
    const remove = (group) => { if (confirm(`Delete "${group.name}"?`)) router.delete(route("admin.customer-groups.destroy", group.id)); };
    return <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-gray-800">Customer Groups</h2>}><Head title="Customer Groups" /><div className="py-8"><div className="mx-auto max-w-7xl sm:px-6 lg:px-8"><div className="overflow-hidden bg-white shadow-sm sm:rounded-lg"><div className="flex flex-col gap-3 border-b p-6 md:flex-row md:items-center"><input className="rounded-md border-gray-300" placeholder="Search name or code..." value={search} onChange={(e) => setSearch(e.target.value)} /><select className="rounded-md border-gray-300" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option value="1">Active</option><option value="0">Inactive</option></select><Link href={route("admin.customer-groups.create")} className="md:ml-auto rounded bg-blue-600 px-4 py-2 text-center text-white">+ Add Customer Group</Link></div><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr><th className="px-6 py-3 text-left">Name</th><th className="px-6 py-3">Discount</th><th className="px-6 py-3">Credit Limit</th><th className="px-6 py-3">Status</th><th className="px-6 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-gray-200">{groups.data.length ? groups.data.map((group) => <tr key={group.id}><td className="px-6 py-4"><div className="font-semibold text-gray-900">{group.name}</div><div className="text-sm text-gray-500">{group.code}</div></td><td className="px-6 py-4 text-sm text-gray-600">{group.discount_type === "percentage" ? `${group.discount_value}%` : group.discount_value}</td><td className="px-6 py-4 text-sm text-gray-600">{group.credit_limit}</td><td className="px-6 py-4"><span className={`rounded px-3 py-1 text-sm ${group.status ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"}`}>{group.status ? "Active" : "Inactive"}</span></td><td className="space-x-2 px-6 py-4 text-right"><Link href={route("admin.customer-groups.edit", group.id)} className="rounded bg-amber-500 px-3 py-1 text-white">Edit</Link><button onClick={() => remove(group)} className="rounded bg-red-600 px-3 py-1 text-white">Delete</button></td></tr>) : <tr><td colSpan="5" className="px-6 py-10 text-center text-gray-500">No groups found.</td></tr>}</tbody></table></div><Pagination links={groups.links} /></div></div></div></AuthenticatedLayout>;
}
