import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout";
import { Head, router, useForm } from "@inertiajs/react";
import { Image, LayoutTemplate, Trash2 } from "lucide-react";

const fieldClass = "w-full rounded-xl border-slate-300 text-sm focus:border-indigo-500 focus:ring-indigo-500";

function BannerForm() {
    const { data, setData, post, processing, reset, errors } = useForm({ badge: "", badge_bn: "", title: "", title_bn: "", highlight: "", highlight_bn: "", subtitle: "", subtitle_bn: "", primary_button_text: "Shop Now", primary_button_text_bn: "এখনই কিনুন", primary_button_url: "/shop", secondary_button_text: "Explore Categories", secondary_button_text_bn: "ক্যাটাগরি দেখুন", secondary_button_url: "/shop", image: null, background_from: "#fff4e9", background_to: "#ffe0bd", text_color: "#102b4e", sort_order: 0, is_active: true });
    const submit = (e) => { e.preventDefault(); post(route("admin.homepage-content.banners.store"), { forceFormData: true, onSuccess: () => reset() }); };
    return <form onSubmit={submit} className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="mb-5 flex items-center gap-2 text-lg font-black"><Image size={20}/> Add Hero Banner</h2><div className="grid gap-4 md:grid-cols-2"><input className={fieldClass} placeholder="Badge" value={data.badge} onChange={e=>setData("badge",e.target.value)}/><input className={fieldClass} placeholder="Main title (English) *" value={data.title} onChange={e=>setData("title",e.target.value)} required/><input className={fieldClass} placeholder="Main title (Bangla)" value={data.title_bn} onChange={e=>setData("title_bn",e.target.value)}/><input className={fieldClass} placeholder="Highlighted title" value={data.highlight} onChange={e=>setData("highlight",e.target.value)}/><input className={fieldClass} type="number" placeholder="Sort order" value={data.sort_order} onChange={e=>setData("sort_order",e.target.value)}/><textarea className={`${fieldClass} md:col-span-2`} rows="3" placeholder="Subtitle" value={data.subtitle} onChange={e=>setData("subtitle",e.target.value)}/><input className={fieldClass} placeholder="Primary button text" value={data.primary_button_text} onChange={e=>setData("primary_button_text",e.target.value)}/><input className={fieldClass} placeholder="Primary URL" value={data.primary_button_url} onChange={e=>setData("primary_button_url",e.target.value)}/><input className={fieldClass} placeholder="Secondary button text" value={data.secondary_button_text} onChange={e=>setData("secondary_button_text",e.target.value)}/><input className={fieldClass} placeholder="Secondary URL" value={data.secondary_button_url} onChange={e=>setData("secondary_button_url",e.target.value)}/><label className="text-sm font-semibold">Banner image<input className="mt-2 block w-full text-sm" type="file" accept="image/*" onChange={e=>setData("image",e.target.files[0])}/></label><div className="grid grid-cols-3 gap-3"><label className="text-xs">From<input className="mt-1 h-10 w-full" type="color" value={data.background_from} onChange={e=>setData("background_from",e.target.value)}/></label><label className="text-xs">To<input className="mt-1 h-10 w-full" type="color" value={data.background_to} onChange={e=>setData("background_to",e.target.value)}/></label><label className="text-xs">Text<input className="mt-1 h-10 w-full" type="color" value={data.text_color} onChange={e=>setData("text_color",e.target.value)}/></label></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={data.is_active} onChange={e=>setData("is_active",e.target.checked)}/> Active</label></div>{Object.keys(errors).length>0&&<p className="mt-3 text-sm text-red-600">Please check the required fields.</p>}<button disabled={processing} className="mt-5 rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">Save Banner</button></form>;
}

function PromotionForm() {
    const { data, setData, post, processing, reset } = useForm({ title: "", title_bn: "", subtitle: "", subtitle_bn: "", button_text: "Shop Now", button_text_bn: "এখনই কিনুন", button_url: "/shop", image: null, theme: "mint", sort_order: 0, is_active: true });
    const submit = (e) => { e.preventDefault(); post(route("admin.homepage-content.promotions.store"), { forceFormData: true, onSuccess: () => reset() }); };
    return <form onSubmit={submit} className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="mb-5 flex items-center gap-2 text-lg font-black"><LayoutTemplate size={20}/> Add Promotion Block</h2><div className="grid gap-4 md:grid-cols-2"><input className={fieldClass} placeholder="Title (English) *" value={data.title} onChange={e=>setData("title",e.target.value)} required/><input className={fieldClass} placeholder="Title (Bangla)" value={data.title_bn} onChange={e=>setData("title_bn",e.target.value)}/><select className={fieldClass} value={data.theme} onChange={e=>setData("theme",e.target.value)}><option value="mint">Mint</option><option value="purple">Purple</option><option value="orange">Orange</option><option value="blue">Blue</option></select><textarea className={`${fieldClass} md:col-span-2`} rows="3" placeholder="Subtitle" value={data.subtitle} onChange={e=>setData("subtitle",e.target.value)}/><input className={fieldClass} placeholder="Button text" value={data.button_text} onChange={e=>setData("button_text",e.target.value)}/><input className={fieldClass} placeholder="Button URL" value={data.button_url} onChange={e=>setData("button_url",e.target.value)}/><input className={fieldClass} type="number" placeholder="Sort order" value={data.sort_order} onChange={e=>setData("sort_order",e.target.value)}/><input className="block w-full text-sm" type="file" accept="image/*" onChange={e=>setData("image",e.target.files[0])}/><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={data.is_active} onChange={e=>setData("is_active",e.target.checked)}/> Active</label></div><button disabled={processing} className="mt-5 rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">Save Promotion</button></form>;
}

export default function Index({ banners = [], promotions = [] }) {
    const remove = (url) => { if (confirm("Delete this homepage item?")) router.delete(url); };
    return <AuthenticatedLayout header={<div><h1 className="text-2xl font-black">Homepage Content</h1><p className="text-sm text-slate-500">Manage hero slider and promotional blocks.</p></div>}><Head title="Homepage Content"/><div className="space-y-8 p-6"><div className="grid gap-6 xl:grid-cols-2"><BannerForm/><PromotionForm/></div><section><h2 className="mb-4 text-xl font-black">Hero Banners</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{banners.map(item=><div key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="h-24 rounded-xl" style={{background:`linear-gradient(120deg,${item.background_from},${item.background_to})`}}/><div className="mt-4 font-black">{item.title} {item.highlight}</div><p className="mt-1 text-xs text-slate-500">Order: {item.sort_order} • {item.is_active?"Active":"Inactive"}</p><button onClick={()=>remove(route("admin.homepage-content.banners.destroy",item.id))} className="mt-4 flex items-center gap-2 text-sm font-bold text-red-600"><Trash2 size={16}/> Delete</button></div>)}</div></section><section><h2 className="mb-4 text-xl font-black">Promotion Blocks</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{promotions.map(item=><div key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="font-black">{item.title}</div><p className="mt-2 text-sm text-slate-500">{item.subtitle}</p><button onClick={()=>remove(route("admin.homepage-content.promotions.destroy",item.id))} className="mt-4 flex items-center gap-2 text-sm font-bold text-red-600"><Trash2 size={16}/> Delete</button></div>)}</div></section></div></AuthenticatedLayout>;
}
