import { Head, router, useForm } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { BadgePercent, Plus, Trash2 } from 'lucide-react';

const money=(v)=>`৳${Number(v||0).toLocaleString('en-BD')}`;
export default function Coupons({coupons,campaigns=[],products=[],categories=[],brands=[],stats={}}){
 const form=useForm({code:'',name:'',type:'percentage',value:10,minimum_order:0,maximum_discount:'',scope_type:'all',scope_ids:[],usage_limit:'',per_customer_limit:1,starts_at:'',ends_at:'',is_active:true,marketing_campaign_id:''});
 const submit=e=>{e.preventDefault();form.post(route('admin.marketing.coupons.store'),{preserveScroll:true,onSuccess:()=>form.reset()});};
 const options=form.data.scope_type==='product'?products:form.data.scope_type==='category'?categories:form.data.scope_type==='brand'?brands:[];
 return <AuthenticatedLayout header={<div><h1 className="text-2xl font-black">Marketing & Coupons</h1><p className="text-sm text-slate-500">Create controlled discounts without changing checkout code.</p></div>}>
 <Head title="Marketing & Coupons"/><div className="space-y-6 p-4 sm:p-6">
 <div className="grid gap-4 sm:grid-cols-3"><Stat label="Active coupons" value={stats.active}/><Stat label="Redemptions" value={stats.redemptions}/><Stat label="Discount given" value={money(stats.discount)}/></div>
 <form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-2"><Plus className="text-teal-700"/><h2 className="text-lg font-black">Create coupon</h2></div>
 <div className="grid gap-4 md:grid-cols-3"><Field label="Code"><input value={form.data.code} onChange={e=>form.setData('code',e.target.value.toUpperCase())} required/></Field><Field label="Name"><input value={form.data.name} onChange={e=>form.setData('name',e.target.value)} required/></Field><Field label="Type"><select value={form.data.type} onChange={e=>form.setData('type',e.target.value)}><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option><option value="free_shipping">Free shipping</option></select></Field>
 <Field label="Value"><input type="number" min="0" step="0.01" value={form.data.value} onChange={e=>form.setData('value',e.target.value)} disabled={form.data.type==='free_shipping'}/></Field><Field label="Minimum order"><input type="number" min="0" value={form.data.minimum_order} onChange={e=>form.setData('minimum_order',e.target.value)}/></Field><Field label="Maximum discount"><input type="number" min="0" value={form.data.maximum_discount} onChange={e=>form.setData('maximum_discount',e.target.value)}/></Field>
 <Field label="Scope"><select value={form.data.scope_type} onChange={e=>form.setData(d=>({...d,scope_type:e.target.value,scope_ids:[]}))}><option value="all">All products</option><option value="product">Selected products</option><option value="category">Selected categories</option><option value="brand">Selected brands</option></select></Field>{form.data.scope_type!=='all'&&<Field label="Applicable items" className="md:col-span-2"><select multiple className="min-h-28" value={form.data.scope_ids.map(String)} onChange={e=>form.setData('scope_ids',[...e.target.selectedOptions].map(o=>Number(o.value)))}>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field>}
 <Field label="Total usage limit"><input type="number" min="1" value={form.data.usage_limit} onChange={e=>form.setData('usage_limit',e.target.value)}/></Field><Field label="Per customer"><input type="number" min="1" value={form.data.per_customer_limit} onChange={e=>form.setData('per_customer_limit',e.target.value)}/></Field><Field label="Campaign"><select value={form.data.marketing_campaign_id} onChange={e=>form.setData('marketing_campaign_id',e.target.value)}><option value="">None</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
 <Field label="Starts at"><input type="datetime-local" value={form.data.starts_at} onChange={e=>form.setData('starts_at',e.target.value)}/></Field><Field label="Ends at"><input type="datetime-local" value={form.data.ends_at} onChange={e=>form.setData('ends_at',e.target.value)}/></Field><label className="flex items-center gap-2 pt-8 font-bold"><input type="checkbox" checked={form.data.is_active} onChange={e=>form.setData('is_active',e.target.checked)}/> Active</label></div>
 {Object.keys(form.errors).length>0&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{Object.values(form.errors)[0]}</div>}<button disabled={form.processing} className="mt-5 rounded-xl bg-teal-700 px-5 py-3 font-black text-white">{form.processing?'Saving...':'Create coupon'}</button></form>
 <div className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-black">Coupons</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-4">Code</th><th>Name</th><th>Offer</th><th>Usage</th><th>Status</th><th></th></tr></thead><tbody>{coupons.data.map(c=><tr key={c.id} className="border-t"><td className="p-4 font-black text-teal-700">{c.code}</td><td>{c.name}</td><td>{c.type==='percentage'?`${c.value}%`:c.type==='fixed'?money(c.value):'Free shipping'}</td><td>{c.used_count}{c.usage_limit?` / ${c.usage_limit}`:''}</td><td>{c.is_active?'Active':'Disabled'}</td><td><button onClick={()=>confirm('Delete unused coupon?')&&router.delete(route('admin.marketing.coupons.destroy',c.id))} className="p-2 text-red-600"><Trash2 size={17}/></button></td></tr>)}</tbody></table></div></div>
 </div></AuthenticatedLayout>;
}
const Field=({label,children,className=''})=><label className={`block ${className}`}><span className="mb-1.5 block text-sm font-bold">{label}</span><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border-slate-300 [&_select]:w-full [&_select]:rounded-xl [&_select]:border-slate-300">{children}</div></label>;
const Stat=({label,value})=><div className="rounded-2xl bg-white p-5 shadow-sm"><BadgePercent className="text-teal-700"/><p className="mt-3 text-sm text-slate-500">{label}</p><p className="text-2xl font-black">{value}</p></div>;
